-- This file should undo anything in `up.sql`
-- DROP TABLE IF EXISTS DeckItems CASCADE;
DROP TABLE IF EXISTS Contains CASCADE;
DROP TABLE IF EXISTS DeckItems CASCADE;
DROP TABLE IF EXISTS Documents CASCADE;
DROP TABLE IF EXISTS Cards CASCADE;
DROP TABLE IF EXISTS Media CASCADE;
DROP TABLE IF EXISTS CardHistory CASCADE;
DROP TABLE IF EXISTS UserConfig CASCADE;